baseurl      = "https://tech.jonsson.io"
title        = "tech.jonsson.io"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My tech thoughts"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Enable the theme toggle
  enableThemeToggle = true
  # Metadata mostly used in document's head
  description = "My tech thoughts"
  keywords = "homepage, blog, tech, network, linux"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "tech.jonsson.io"
    subtitle = "My tech encounters"
    keywords = "tech, linux, network, computer"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sudo reboot"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # Social icons
  [[params.social]]
    name = "mastodon"
    url  = "https://social.linuxburken.se/@zooper"

  [[params.social]]
    name = "github"
    url  = "https://github.com/zooper"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tomas-jonsson-b3522925/"

  [[params.social]]
    name = "twitter"
    url  = "https://www.twitter.com/tomas_jonsson"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/me"


